### ISSUE TITLE
Backport Libadwaita to EL9

### ISSUE THREAD

**Issue by nothingneko** [tau-OS/meta#11]
### Problem

tauOS Specific apps cannot be installed on Workstation due to a lack of Libadwaita

### Proposal

Backport Libadwaita to EL9

### Prior Implementations (Optional)

Libadwaita is not in EPEL or RPMFusion for EL

**Comment by lainsce** [comment]
Is this relevant still?

**Comment by nothingneko** [comment]
Until we port settings to libhelium, yes.

**Comment by nothingneko** [comment]
Closing until v1 wraps. Will revisit EL support after.
