### ISSUE TITLE
Ship Fermion instead of GNOME Terminal

### ISSUE THREAD

**Issue by lainsce** [tau-OS/meta#15]
Fermion is our homegrown app, and aligns with our vision and interface guidelines for tauOS apps.

**Comment by nothingneko** [comment]
Is it in repo?

**Comment by lainsce** [comment]
It needs a spec file if doesn't have one, and then change the ostree pkgs.

**Comment by lainsce** [comment]
Also, it needs for Fermion specifically that we get jamie's VTE fork packaged and it replaces normal VTE until Jamie's additions are merged upstream.

**Comment by ItsJamie9494** [comment]
You would need me to package VTE for you. I would also not use Fermion right now, it still has major bugs.

**Comment by ItsJamie9494** [comment]
> Also, it needs for Fermion specifically that we get jamie's VTE fork packaged and it replaces normal VTE until Jamie's additions are merged upstream.

As of today, the changes were merged upstream. You'll have to use the master branch of upstream, but it is merged

**Comment by nothingneko** [comment]
Fermion is not ready to be included in tau, and likely needs a refactor before additional consideration. This is of extremely low priority.

**Comment by nothingneko** [comment]
Accelerator closes this
