### ISSUE TITLE
Ship Modi instead of GNOME Photos & Eye of GNOME

### ISSUE THREAD

**Issue by lainsce** [tau-OS/meta#16]
Modi is our homegrown app, and aligns with our vision and interface guidelines for tauOS apps.

**Comment by nothingneko** [comment]
Is it in repo?

**Comment by lainsce** [comment]
It needs a spec file if doesn't have one, and then change the ostree pkgs.

**Comment by nothingneko** [comment]
EOG is being deprecated, this is gonna get fast-tracked

**Comment by lainsce** [comment]
GNOME Photos is afaik without a maintainer, so ultra fast-tracking

**Comment by lleyton** [comment]
What’s the completion status of Modi?

**Comment by lainsce** [comment]
Needs just a QA session and a specfile

**Comment by lleyton** [comment]
QA and flatpak it, I think you can handle that

**Comment by nothingneko** [comment]
Zoom is the only issue. Reset zoom when image is changed and Modi is golden!
