### ISSUE TITLE
System Bug Reporting App

### ISSUE THREAD

**Issue by lleyton** [tau-OS/meta#19]
Currently, if a user wants to report a bug, they'll need to go to our GitHub org, make a GitHub account if they don't already have one, and open an issue on the appropriate repository. This workflow is not ideal for non-technical users, which might be discouraged from opening bug reports due to the high barrier of entry. We should ship a built-in bug reporting app (see Feedback Assistant on macOS) to improve this process.

**Comment by korewaChino** [comment]
Why can't we just use ABRT?

**Comment by nothingneko** [comment]
>Why can't we just use ABRT?

ABRT is a poorly designed experience on the user side.

**Comment by lleyton** [comment]
something like ABRT would be ideal, although not all bugs are necessarily crashes

**Comment by nothingneko** [comment]
Is this completed?

**Comment by lainsce** [comment]
Yes, it's Mondai.

However it seems Mondai is still being developed.

**Comment by lexisother** [comment]
Closing as completed.

Ref:
![Image](https://user-images.githubusercontent.com/54973868/230390704-be3fb895-5799-4691-a751-f08b2f743cc9.png)
URL: https://discord.com/channels/957104883490775061/957104884799393834/1093525048729534576
