### ISSUE TITLE
ISO file for download isn't the right one

### ISSUE THREAD

**Issue by BioHazard1282** [tau-OS/meta#2]
Downloaded `Fedora-Server-netinst-x86_64-35-1.2.iso` from `https://sourceview.innatical.com/tauos/beta`,
Tried to load GRUB in a virtual machine and it wasn't the right menu.

Try silverblue.

**Comment by jadeastar** [comment]
Hi BioHazard1282, You can follow the progress of this issue on [Sourceview.](https://sourceview.innatical.com/tauos/beta/-/issues/1) Thank you again!

**Comment by jadeastar** [comment]
Close for moving efforts
