### ISSUE TITLE
tauOS User Repository

### ISSUE THREAD

**Issue by lleyton** [tau-OS/meta#22]
One of the things I adore about Arch is the AUR, it's extremely simple to publish a package, as evident by the abundance of packages in it. This would make it easier for users to package software and drivers (important for exotic hardware) that Fedora or tauOS do not offically support. Security is going to be a major issue in this one, so let's keep that in mind in our design.

**Comment by korewaChino** [comment]
This could also be integrated into Ultramarine too.

**Comment by lleyton** [comment]
Yup, I think it should

**Comment by nothingneko** [comment]
The security concerns leads back to a levels of trust idea I had a few months ago. It's like this

Full Trust (Confirmed Safe) - Fyra-provided packages, RPM-Fusion, EPEL, SIG Packages, Catalogue Apps and Fedora packages
Medium Trust (Likely Safe) - Flathub, Snapcraft
Low Trust (Potentially Dangerous)- AppImages, loose binaries

Lower levels of trust would have some sort of safeguard like Gatekeeper on macOS. We could also do something like Notarization on macOS, apps from Flathub and the internet can apply for signing by us to achieve a higher level of trust

**Comment by korewaChino** [comment]
> Lower levels of trust would have some sort of safeguard like Gatekeeper on macOS. We could also do something like Notarization on macOS, apps from Flathub and the internet can apply for signing by us to achieve a higher level of trust

Wouldn't this impede on the user's freedom? We shouldn't really try to stop people from running untrusted software and implement these levels of trust, for the sake of giving people the choice to which software they want to run.

In my case I run a lot of software that would be considered "untrusted" by Fyra standards that I use daily. This includes third-party AppImages, Crates from crates.io, Flatpaks from non-Flathub repos, and even "loose" binaries like standalone BuildKit. Trying to gatekeep users from using unknown software would make them think we are forcing them to use something that they aren't comfortable with.

As the maintainer of Ultramarine, I completely disagree on implementing trust levels, we can have signed binaries, but we absolutely should **_NOT_** tell users what software they can run. Users should be responsible for their own opsec.

**Comment by nothingneko** [comment]
Does Lunapkg close this?

**Comment by korewaChino** [comment]
> Does Lunapkg close this?

I guess. The issue here is that we need to actually have a working product first.

**Comment by nothingneko** [comment]
We're cancelling this plan, we're competing with ourselves too much, let's not Chuck-E-Cheese ourselves
