### ISSUE TITLE
Better Laptop Suppport

### ISSUE THREAD

**Issue by ItsJamie9494** [tau-OS/meta#6]
Newer versions of tauOS don't wake up from sleep on my personal laptop (a Lenovo ThinkBook 13s). Older versions did. I'm not sure what change prompted this, but I believe we need to fix this regression.

**Comment by nothingneko** [comment]
I have a 13s and it works on my system /s

**Comment by ItsJamie9494** [comment]
I have a 13s Gen3, you have a Gen2

**Comment by ItsJamie9494** [comment]
its gone now anyways so dum laptop momento

**Comment by nothingneko** [comment]
GNOME 42 is generally buggy with laptops and displays, I’d report it upstream

**Comment by ItsJamie9494** [comment]
The latest update is bringing this issue back

**Comment by nothingneko** [comment]
No info - closing
