### ISSUE TITLE
Music App

### ISSUE THREAD

**Issue by ItsJamie9494** [tau-OS/meta#8]
### Problem

tauOS iirc ships with Rhythmbox music player, which has one of the worst UIs I've seen. GNOME Music looks better, but has no functionality.

### Proposal

I propose forking the elementary OS Odin music player, and updating it for GTK4 and LibAdwaita.

**Comment by nothingneko** [comment]
We ship GNOME music. Although Rhythmbox should be installed if an iPod or other MP3 player is connected

**Comment by ItsJamie9494** [comment]
Not by default, it should be installed when the mp3 device is connected.

However, GNOME music by default has limited functionality. I'd like Rhythmbox functionality with elementary Music or GNOME Music UI

**Comment by lleyton** [comment]
I propose that we ship [Amberol](https://flathub.org/apps/details/io.bassi.Amberol).

Not to mention that the author's screenshots have songs by Mori Calli— Demondice, which is based.

**Comment by nothingneko** [comment]
I think we should ship a music app that will show the user's music inside the app

**Comment by lleyton** [comment]
It's perfect besides that, showing the music folder by default would be a simple PR.

**Comment by nothingneko** [comment]
I believe the dev refuses to do that

**Comment by lleyton** [comment]
source?

**Comment by nothingneko** [comment]
The delusions of grandeur statement and the fact the file opening has a proper UI

**Comment by lleyton** [comment]
I don't think that would suggest an opinion either way, an issue was opened 1 hour ago, asking the [same thing](https://gitlab.gnome.org/World/amberol/-/issues/92), so we'll see. Worst case scenario, patch.

**Comment by lleyton** [comment]
And wow, that was quick

**Comment by nothingneko** [comment]
Patch it @ItsJamie9494

**Comment by lleyton** [comment]
https://gitlab.gnome.org/World/amberol/-/issues/24

The author cites two issues:
1. It would not be practical to do in sandboxed applications.
2. Building a "music DB" is out of scope, which is required if it is sandboxed.

Luckily, we don't play by their rules.

**Comment by nothingneko** [comment]
Every other sandboxed music app has never had issues with it

**Comment by lleyton** [comment]
I'm only stating what the author has said, although the test case that would break the functionality that the author referenced is considered user error in my opinion. Someone modifying the permissions to remove the access to the playlist, or library files is an intentional action.

**Comment by ItsJamie9494** [comment]
Literally just use flatpak portals and you don't need any sandboxing shit

**Comment by nothingneko** [comment]
It's a nonissue

**Comment by lainsce** [comment]
We should ship a basic music app just for people to preview music they receive in other places by friends or stuff; leave Album management to the user's choice of service like e.g. Spotify.

**Comment by nothingneko** [comment]
I think albums can also be handled locally by this app

**Comment by lleyton** [comment]
Out of scope, album management is a beast within itself. The default music player should only play music files, show basic metadata, and maybe allow for simple playlists.

**Comment by lainsce** [comment]
Victrola is our app. Closing this. :)
